### ISSUE TITLE
framework not found Pods

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [kylef/cocoapods-deintegrate#6]
I had a project created in Xcode 6.2 with CocoaPods 0.36. I deintegrated it but when I build the project now I get the error **framework not found Pods**.

**Comment by kylef** [comment]
I'm unable to produce this issue, can you upload an example project that exhibits this problem?

**Comment by Isuru-Nanayakkara** [comment]
I have uploaded a test project [here](https://www.dropbox.com/s/p9nbbmltb020rpf/PodRemove.zip?dl=0). 

I found out how to remove the remaining stuff manually. Here are the steps I took. Again, I'm using Xcode 6.2 and CocoaPods 0.36.

1 . Run `pod deintegrate` and it was executed successfully.
```
Isurus-Mac-mini:PodRemove Isuru$ pod deintegrate
Deintegrating PodRemove.xcodeproj
Deintegrating target PodRemove
Deleted 1 'Copy Pods Resources' build phases.
Deleted 1 'Check Pods Manifest.lock' build phases.
Deleted 1 'Embed Pods Frameworks' build phases.
Deintegrating target PodRemoveTests
Deleting Pod file references from project
- Pods.debug.xcconfig
- Pods.release.xcconfig
Deleted 1 empty `Pods` groups from project.
Removing `Pods` directory.

Project has been deintegrated. No traces of CocoaPods left in project.
Note: The workspace referencing the Pods project still remains.
```

2 . Deleted the following three files manually from the Finder.
```
PodRemove.xcworkspace
Podfile.lock
Podfile
```

3 . Opened the project from *PodRemove.xcodeproj*, build it and got the error **framework not found Pods**.

4 . The *Pods.framework* was still present in the **Linked Frameworks and Libraries** list. Removed it. Build it and success!

5 . I couldn't reproduce this in my last attempt. But one time previously the *Copy Pods Resources* wasn't automatically removed from the **Build Phases** list and it would give me another build error. Had to remove it manually as well.

**Comment by kylef** [comment]
This should have been fixed for a while, can you confirm @Isuru-Nanayakkara?

**Comment by rajohns08** [comment]
I'm still having to manually go through the process that @Isuru-Nanayakkara mentioned.

**Comment by BigPun86** [comment]
+1
